# This rule is not used by the project custom-resource-def itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to workloads.example.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: custom-resource-def
    app.kubernetes.io/managed-by: kustomize
  name: partitionedworkload-viewer-role
rules:
- apiGroups:
  - workloads.example.com
  resources:
  - partitionedworkloads
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - workloads.example.com
  resources:
  - partitionedworkloads/status
  verbs:
  - get
