---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - list
  - watch
  - get
  - create
  - update
  - delete
- apiGroups:
  - workloads.example.com
  resources:
  - partitionedworkloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.example.com
  resources:
  - partitionedworkloads/finalizers
  verbs:
  - update
- apiGroups:
  - workloads.example.com
  resources:
  - partitionedworkloads/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
