apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: custom-resource-def
    app.kubernetes.io/managed-by: kustomize
  name: custom-resource-def-controller-manager
  namespace: custom-resource-def-system
