apiVersion: v1
kind: Pod
metadata:
  name: oom-pod
spec:
  containers:
  - name: memory-hog
    image: python:3.9-slim
    command: ["python3", "-c", "a = ['x' * 1024 * 1024 for _ in range(10000000)]"]
    resources:
      limits:
        memory: "64Mi"  # Set a low memory limit