apiVersion: workloads.example.com/v1
kind: PartitionedWorkload
metadata:
  name: my-workload
  namespace: custom-resource-def-system
spec:
  replicas: 4
  podTemplate:
    containers:
    - name: nginx
      image: nginx:1.19
  partitionCount: 0
