apiVersion: v1
kind: Secret
metadata:
  name: custom-resource-def-controller-manager-token
  namespace: custom-resource-def-system
  annotations:
    kubernetes.io/service-account.name: custom-resource-def-controller-manager
type: kubernetes.io/service-account-token