apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "partitioned-workload.fullname" . }}
  labels:
    {{- include "partitioned-workload.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "partitioned-workload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "partitioned-workload.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "partitioned-workload.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--health-probe-bind-address=:8081"
            - "--metrics-bind-address=:8080"
          ports:
            - name: metrics
              containerPort: 8080
              protocol: TCP
            - name: health
              containerPort: 8081
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # Volume mount for tmp when using readOnlyFileSystem security enhancement
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
      # Volume for temporary files when using readOnlyRootFilesystem
      volumes:
        - name: tmp-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}