apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "partitioned-workload.fullname" . }}
  labels:
    {{- include "partitioned-workload.labels" . | nindent 4 }}
rules:
- apiGroups: ["workloads.example.com"]
  resources: ["partitionedworkloads"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["workloads.example.com"]
  resources: ["partitionedworkloads/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["workloads.example.com"]
  resources: ["partitionedworkloads/finalizers"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["apps"]
  resources: ["controllerrevisions"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "partitioned-workload.fullname" . }}
  labels:
    {{- include "partitioned-workload.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "partitioned-workload.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "partitioned-workload.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
